# Czech translation of django-otp.
# Copyright (C) Listed translators
# This file is distributed under the same license as the django-otp package.
#
msgid ""
msgstr ""
"Project-Id-Version: django-otp master\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-11-09 12:20-0600\n"
"PO-Revision-Date: 2022-11-09 19:43+0100\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: src/django_otp/forms.py:59
msgid "Please enter your OTP token."
msgstr "Prosím zadejte token, který Vám vygenerovalo Vaše zařízení."

#: src/django_otp/forms.py:60
#, python-brace-format
msgid "Error generating challenge: {0}"
msgstr "Chyba při generování výzvy: {0}"

#: src/django_otp/forms.py:61
msgid "The selected OTP device is not interactive"
msgstr "Vybrané OTP zařízení není interaktivní"

#: src/django_otp/forms.py:62
#, python-brace-format
msgid "OTP Challenge: {0}"
msgstr "OTP výzva: {0}"

#: src/django_otp/forms.py:63
msgid "Invalid token. Please make sure you have entered it correctly."
msgstr ""
"Chybný token. Prosím ujistěte, že jste vložili platný token."

#: src/django_otp/forms.py:65
#, python-format
msgid ""
"Verification temporarily disabled because of %(failure_count)d failed "
"attempt, please try again soon."
msgid_plural ""
"Verification temporarily disabled because of %(failure_count)d failed "
"attempts, please try again soon."
msgstr[0] ""
"Ověření je dočasně vypnuto z důvodu %(failure_count)d neúspěšného pokusu. "
"Zkuste to později."
msgstr[1] ""
"Ověření je dočasně vypnuto z důvodu %(failure_count)d neúspěšných pokusů. "
"Zkuste to později."

#: src/django_otp/forms.py:68
msgid "Verification of the token is currently disabled"
msgstr "Ověření tokenu je momentálně vypnuté"

#: src/django_otp/templates/otp/admin111/login.html:38
msgid "Please correct the error below."
msgstr "Prosím opravte následující chybu."

#: src/django_otp/templates/otp/admin111/login.html:38
msgid "Please correct the errors below."
msgstr "Prosím opravte následující chyby."

#: src/django_otp/templates/otp/admin111/login.html:54
#, python-format
msgid ""
"You are authenticated as %(username)s, but are not authorized to access this "
"page. Would you like to login to a different account?"
msgstr ""
"Jste přihlášeni jako %(username)s, ale nemáte oprávnění přístupu na tuto "
"stránku. Přejete si přihlásit s jiným účtem?"

#: src/django_otp/templates/otp/admin111/login.html:74
msgid "OTP Device:"
msgstr "Zařízení OTP:"

#: src/django_otp/templates/otp/admin111/login.html:79
msgid "OTP Token:"
msgstr "OTP Token:"

#: src/django_otp/templates/otp/admin111/login.html:84
msgid "Forgotten your password or username?"
msgstr "Zapoměli jste uživatelské jméno nebo heslo?"

#: src/django_otp/templates/otp/admin111/login.html:88
msgid "Log in"
msgstr "Přihlásit"

#: src/django_otp/templates/otp/admin111/login.html:90
msgid "Get OTP Challenge"
msgstr "Obdržet OTP výzvu"
